### ISSUE TITLE
Add stream

### ISSUE THREAD

**Issue by fire** [cabol/nebulex#10]
How difficult is it to add stream?

https://hexdocs.pm/ecto/Ecto.Repo.html#c:stream/2

**Comment by cabol** [comment]
@fire I think you should open the issue in [nebulex_ecto](https://github.com/cabol/nebulex_ecto/issues/4)

**Comment by cabol** [comment]
I moved this issue to [nebulex_ecto issues](https://github.com/cabol/nebulex_ecto/issues/5)
