### ISSUE TITLE
Migrating to v2 link is broken

### ISSUE THREAD

**Issue by yatender-oktalk** [cabol/nebulex#103]
[v2 upgrade link ](https://hexdocs.pm/nebulex/migrating-to-v2.html)

I was using nebulex v1.2.2 but with that version shards 0.6 was giving issue while compiling with OTP 23.
Then while upgrading shards was fine but decorator issue came up and there is a broken link for documentation.
Please guide me where I can check the link to upgrade to v2.

**Comment by cabol** [comment]
I think this is the same issue as #102, isn't it? This is the link anyway: https://hexdocs.pm/nebulex/2.0.0-rc.2/migrating-to-v2.html#content

**Comment by yatender-oktalk** [comment]
Thank you @cabol for quick help.
