### ISSUE TITLE
Bug on boolean values

### ISSUE THREAD

**Issue by escobera** [cabol/nebulex#111]
Hello there,

I have a function similar to this one:

```elixir
@decorate cacheable(cache: MyCache, key: id)
def good?(id) do
  HttpClient.get() 
  |> handle_response()
end
```

When this function returns `false`, even though the value gets cached, the next time it is called it won't use the cached value and issue another http request.

I tracked down the problem to this code:

https://github.com/cabol/nebulex/blob/7dcdd306ffcc7e97db41c31a10822c04ff44741e/lib/nebulex/caching.ex#L481-L484

Problem here is if `cache.get(key, opts)` evals to false (this is my case) this line `value = cache.get(key, opts)` evals to false, you can test in iex with: 

```elixir
iex(1)> x = false
false
```

Since this is not a pure function and the value gets cached I wasn't able to make a failing test case for it, but it seems that to fix this you can change those lines to: 

```elixir
case cache.get(key, opts) do
  nil -> Caching.eval_match(unquote(block), match, cache, key, opts)
  value -> value
end
```

I ran the tests here after the change and they pass.

**Comment by cabol** [comment]
Thanks for report the issue, question, would you like to send a PR with the fix? Otherwise, NP, I can take a look at it and apply the fix. Let me know, stay tuned! Thanks again!

**Comment by escobera** [comment]
I'm trying to come up with a test case for it. I'll send the PR as soon as possible.

**Comment by cabol** [comment]
The PR LGTM! It is merged, I will publish a new release this weekend! Thank you for fixing the issue 👍 !!
