### ISSUE TITLE
Use of :ets reference after delete

### ISSUE THREAD

**Issue by escobera** [cabol/nebulex#120]
Hello there, after some time running I'm being hit with some argument errors here.

```
** (ArgumentError) argument error
--
  | (stdlib 3.14) :ets.take(#Reference<0.430097009.965083137.200472>, "SISTJ@1\|\|20120110078872")
  | (nebulex 2.0.0) lib/nebulex/adapters/local.ex:695: Nebulex.Adapters.Local.pop_entry/4
  | (nebulex 2.0.0) lib/nebulex/adapters/local.ex:420: Nebulex.Adapters.Local.gen_fetch/5
  | (nebulex 2.0.0) lib/nebulex/adapters/local.ex:412: Nebulex.Adapters.Local.do_get/4
  | (nebulex 2.0.0) lib/nebulex/adapters/local.ex:401: Nebulex.Adapters.Local.get/3
  | (antecedentes_api 0.1.0) lib/antecedentes_api/servicos/processos_api.ex:26: AntecedentesApi.Servicos.ProcessosApi.carregar_dados_processo/2
  | (antecedentes_api 0.1.0) lib/antecedentes_api/filtros/filtrador.ex:53: AntecedentesApi.Filtros.Filtrador.executar_filtros_de_processo/1
  | (antecedentes_api 0.1.0) lib/antecedentes_api/filtros/filtrador.ex:14: AntecedentesApi.Filtros.Filtrador.filtrar/1
  | Function: #Function<5.84974940/0 in AntecedentesApi.Etl.handle_cast/2>
  | Args: []
```
I have 10 different tasks acessing the cache concurrently. Maybe the local adapter has an old invalid reference when it tries to access the backend? Is it preventable?

**Comment by cabol** [comment]
@escobera good catch! I was able to reproduce the issue, I created a separate issue describing the scenario and also pushed the fix to the `master` branch, which should fix this problem too. Please try it out and let me know if it works for you. If so, I will publish a new release this weekend with the last changes.

**Comment by escobera** [comment]
I'm deploying pointing to master, will run some heavy stuff here and report back. Thank you!

**Comment by escobera** [comment]
Everything looks fine for now, I'm closing this. Thanks a lot! =)
