### ISSUE TITLE
Hits/Misses statistics not updated when using get_all

### ISSUE THREAD

**Issue by liamdasilva** [cabol/nebulex#125]
Hi there :)

I have a cache that has statistics enabled with stats: true in the config
```
config :my_app, MyCache, [
  primary: [
    stats: true,
    # When using :shards as backend
    backend: :shards,
    # GC interval for pushing new generation: 12 hrs
    gc_interval: :timer.hours(12),
    # Max 10,000 entries in cache
    max_size: System.get_env("CACHE_LIMIT", "10000") |> String.to_integer(),
    # Max 2 GB of memory
    allocated_memory: 2_000_000_000,
    # GC min timeout: 10 sec
    gc_cleanup_min_timeout: :timer.seconds(10),
    # GC min timeout: 10 min
    gc_cleanup_max_timeout: :timer.minutes(10)
  ]
]
```
and with periodic measurements enabled in telemetry
```
defp periodic_measurements do
    [
      {MyCache, :dispatch_stats, []}
    ]
  end
```
This produces stats perfectly fine when I use MyCache.get/1, however when using MyCache.get_all/1 I noticed that the hit/miss stats are not updated. Am I doing something wrong or is this a known issue and not supported yet?

Thanks!

**Comment by cabol** [comment]
You're absolutely right, with `get_all` if a bit thicker because we have to compare which keys were found and which ones weren't, and based on that, update the `:hits` and `:misses`. But I will take a look at it. Thanks!

**Comment by cabol** [comment]
Hey @liamdasilva 👋 

I found the issue and pushed the fix already to the master branch. Please try it out and let me know if it works for you.

PD: I'll ship a new release soon!

**Comment by liamdasilva** [comment]
Wow that was fast, thanks so much Carlos :) I'll test it out and let you know

**Comment by liamdasilva** [comment]
Yup, works great, thanks so much :)
