### ISSUE TITLE
cache_put does not work when passing a list of keys

### ISSUE THREAD

**Issue by cschmatzler** [cabol/nebulex#127]
Hi!

Checking out the library right now and trying to follow the examples.
Right in the README, this is shown:
```
 @decorate cache_put(
              cache: Cache,
              keys: [{User, usr.id}, {User, usr.username}],
              match: &match_update/1
            )
  def update_user(%User{} = usr, attrs) do
    usr
    |> User.changeset(attrs)
    |> Repo.update()
  end
```

I cannot get this working. Running an `update` method on a record with `cache_put(cache, key: {User, usr.id}, match: &match_update/1)` works just fine and updates the one key in the cache with the updated record.
Passing multiple keys as a list does add one to `Cache.count_all`, no matter how many keys are in the list, and does not update the `{User, usr.id}` key at all.

Not sure how to provide a minimal reproduction because I essentially copy and pasted the README.

Cheers

**Comment by cschmatzler** [comment]
Added a test for this in https://github.com/cschmatzler/nebulex/commit/9c93e4b2d4b079d79716f3dd99cbd46dd4042636 which expectedly fails.

**Comment by cabol** [comment]
Hey 👋 !

You are facing that issue with the `cache_put` because the `:keys` option is only available for `cache_evict` currently (you can check the docs, and the option is only for `cache_evict`).

However, it could be possible to extend the `:keys` option to the rest of the caching annotations, but that would be an additional improvement (I will check and open a separate issue for it).

Thanks.

**Comment by cschmatzler** [comment]
Hi! 
Thank you for your quick reply.

In that case, the quick start example in the README is incorrect:
https://github.com/cabol/nebulex/blob/ca7e0c47fb1a155c226bfa97e6ceeb2cb08bbe0f/README.md?plain=1#L169

I'll see if I can help you out and at least get the README updated over the weekend.
Other than that, being able to put multiple keys on update like in that example would be a great enhancement.

Have a great day!

**Comment by cabol** [comment]
Yeah, you're absolutely right, that is a mistake in the README, I will fix it, and yes, totally agree, I think that would be a good improvement, will try to work on it this weekend!

**Comment by cabol** [comment]
Created Issue #128

**Comment by cabol** [comment]
Hey! I pushed to the master branch some changes adding support for `:keys` option in the `cache_put` annotation. Please check it out and let me know if you face any issues. Stay tuned!

**Comment by cschmatzler** [comment]
Hey Carlos! master branch looks great and the code I had in mind works well now.
Really appreciate your super quick response and the nice enhancement.

Thanks for the great library and I hope you have a wonderful week!

**Comment by cabol** [comment]
Thanks 🙇‍♂️ !! Will publish a new release with this enhancement very soon!!
