### ISSUE TITLE
Performance penalty when using Multilevel + Local + Redis adapters

### ISSUE THREAD

**Issue by saulbensach** [cabol/nebulex#138]
Hey.

Today I found one of the bottlenecks that we had on our application.
For giving a bit of context we are using `Nebulex.Adapters.Multilevel` with `Nebulex.Adapters.Local` as L1 and the `NebulexRedisAdapter` as L2. So making a bit of tracing with OpenTelemetry and Zipkin I got this result.

![image](https://user-images.githubusercontent.com/13313290/137758876-70f8bf7c-7b27-4a98-872a-5b8fba0e3c65.png)

As you can see the get_all gets transformed in at least 1 get per key, and as you can imagine having also Redis this gives us a pretty big performance penalty due to having to do a ETS call + Redis call for each element.

This happens because the implementation for the Multilevel and ETS get_all is transformed in many gets. I understant that this choice is made because having to generate dynamic match_spec has its complications.

If you want I can provide a repo demonstrating this behaviour, but that can take some evenings :P

Waiting for your feedback.

**Comment by saulbensach** [comment]
Hey @cabol sorry but I'm working on pushing software, so I dont have any time :(

**Comment by cabol** [comment]
Closing this issue since no more feedback was received. Feel free to re-open if there are more findings or feedback about it.
