### ISSUE TITLE
Document test env setup with decorators?

### ISSUE THREAD

**Issue by atavistock** [cabol/nebulex#155]
I'm able to easily switch adapters before the supervision tree starts, but I'm somewhat confused on the best approach to the decorator pattern and how it might work with different implementations.

In any given module I have `@decorator cacheable(cache: MyApp.Cache.Local)`.  The problem is that `MyApp.Cache.Local`  is the real implementation, not an alias or a mock.   I know I could do something messy checking the `Mix.env` and setting an appropriate alias in each module.  But Is there a good way to define the mock class at a higher level like in application.ex or config.ex?

**Comment by suzdalnitski** [comment]
Having the exact same issue... Is there a way to use the Null Adapter with decorators?

**Comment by cabol** [comment]
Hey 👋 !!

Well, the main limitation is decorations are evaluated in compilation time, so yes, the cache you pass there is the real implementation. I think there may be several ways to address this, but let me mention a workaround I've used myself in these cases. You can add a configuration parameter at the app level to define the adapter to use, for example:

```elixir
adapter = Application.get_env(:my_app, :cache_adapter, Nebulex.Adapters.Local)

defmodule MyApp.Cache do
  otp_app: :my_app,
  adapter: adapter
end
```

And then you can use the different config files depending on the environment, for example in the `test.exs` you could:

```elixir
config :my_app,
  cache_adapter: Nebulex.Adapters.Nil
```

It is a very naive/simple workaround but it has worked for me, maybe not the best, but it helps to address the need of having different adapters depending on the environment.

I will think if there is something else we can do about it, but in the meantime let me know if the workaround works for you. Thanks!

**Comment by suzdalnitski** [comment]
@cabol 

Thanks for a quick reply!

Do you think it may be possible to modify the decorator to accept a function returning the cache at runtime?

Something among the lines of:

```elixir
defp cache, do: Application.fetch_env!(:my_app, :cache)

@decorate cacheable(cache: &cache/1)
def get_account(id) do
  ...
end
```

Would you be interested in a PR for this feature?

**Comment by suzdalnitski** [comment]
@cabol 

Let me know if I should make any changes to my PR: https://github.com/cabol/nebulex/pull/156

**Comment by suzdalnitski** [comment]
You still need to start the cache, here's how I'm doing this in tests (based on the `DataCase`):

```elixir
defmodule MyApp.CacheCase do
  use ExUnit.CaseTemplate

  alias Ecto.Adapters.SQL.Sandbox

  using do
    quote do
      import Ecto
      import Ecto.Changeset
      import Ecto.Query
    end
  end

  setup _ do
    # Ecto setup
    :ok = Sandbox.checkout(MyApp.Repo)

    Sandbox.mode(MyApp.Repo, {:shared, self()})

    # Start the cache
    {:ok, cache_pid} = MyApp.Cache.LiveCache.start_link()

    Application.put_env(:my_app, :cache, MyApp.Cache.LiveCache)

    # Stop the cache on exit
    on_exit(fn ->
      if Process.alive?(cache_pid), do: Process.exit(cache_pid, :normal)

      Application.put_env(:my_app, :cache, MyApp.Cache.TestCache)
    end)

    :ok
  end
end
```

The caches are defined as:
```elixir
defmodule MyApp.Cache.LiveCache do
  use Nebulex.Cache,
    otp_app: :my_app,
    adapter: Nebulex.Adapters.Local
end

defmodule MyApp.Cache.TestCache do
  use Nebulex.Cache,
    otp_app: :my_app,
    adapter: Nebulex.Adapters.Nil
end

```

Then make sure that you're running this as async within your tests:

```elixir
use MyApp.CacheCase, async: false
```

**Comment by suzdalnitski** [comment]
@cabol 
Is there anything that can be improved in the PR? Thanks!

**Comment by suzdalnitski** [comment]
@cabol That's great, thank you!

**Comment by cabol** [comment]
Closing this issue since some workarounds have been shared and the ability to resolve the cache in decorators at runtime. However, for Nevbulex v3.0.0 I'm planning to address this better, not only with the decorators but in general, so suggestions or ideas are welcome, feel free to open an issue with the proposal.
