### ISSUE TITLE
Duplicate data keys when put in replicated cache when start app

### ISSUE THREAD

**Issue by thachtan** [cabol/nebulex#158]
Hi team, i have problem with duplicate data in replicated cache.

I start two node same time and put data concurrently and a have duplicate in both node.

I have small [repo](https://github.com/tanthachiplus/demo_nebulex_lock_key.git) to describe it.

I add data in small setup process.

<img width="649" alt="Screen Shot 2022-06-02 at 11 55 49" src="https://user-images.githubusercontent.com/50437785/171555919-1bd0cd26-b474-4127-9a24-c5182ecad8e9.png">

and get duplicate keys with get match.

<img width="582" alt="Screen Shot 2022-06-02 at 11 56 55" src="https://user-images.githubusercontent.com/50437785/171556005-1d6f72fa-fc5d-4a5d-88ec-fe6655d04aa2.png">

**Comment by cabol** [comment]
Hey! Let me check it out and will try to get back to you soon!

**Comment by cabol** [comment]
Hey! I've pushed some fixes and improvements to the master branch, may you please try it out and see if you get the same error, stay tuned, thanks!

**Comment by thachtan** [comment]
Great, It worked!!!

It clear old cache gen.

Thanks for your help ^^ <3 <3 <3

**Comment by cabol** [comment]
Glad to hear that 😄 ! And thanks to you too, because of your tests, we have been able to identify issues, corner cases, and also possible improvements, which is great, so thanks, stay tuned 👍

**Comment by cabol** [comment]
BTW, just published a new release with these changes as well as with other features!
