### ISSUE TITLE
Cannot use variables in decorator keys

### ISSUE THREAD

**Issue by atavistock** [cabol/nebulex#161]
In the documentation there are many occurrences of using the cacheable decorator where a key is specified

For example:
```
@decorate cacheable(cache: Cache, key: {Account, email})
def get_account(email, include_users?) do
  # the logic for retrieving the account ...
end
```

In these cases (at least for me) the compiler rightly complains that `email` doesn't exist.  Is this intended to be an atom and not a bare variable?

**Comment by cabol** [comment]
Hi 👋 !!

That's weird, I've tried the same code snippet you put here and worked, no warnings or error whatsoever, in fact, I have several similar annotated function and haven't had a warning. So, what version of Nebulex and Elixir are you using? So I can try to reproduce it.
