### ISSUE TITLE
Adapter configuration per-env?

### ISSUE THREAD

**Issue by tpitale** [cabol/nebulex#171]
Is it, or would it be, possible to configure the adapter based on the environment? E.g., dev uses a local cache, but released environments use the redis adapter.

**Comment by cabol** [comment]
Hey! I think this issue https://github.com/cabol/nebulex/issues/155 is related to this, let me know if that helps, otherwise, we can continue the discussion here.

**Comment by tpitale** [comment]
Thanks @cabol!
