### ISSUE TITLE
[multiple clause functions] Cannot use ignored variables in decorator keys

### ISSUE THREAD

**Issue by JVZELLER** [cabol/nebulex#173]
### Current behavior
When using multiple clause functions, it seems not possible to specify a key when one of the clauses ignores a given argument.

For example:
```elixir
defmodule MyApp.Info do
  @moduledoc false

  use Nebulex.Caching
  alias MyApp.Cache

  @ttl :timer.hours(1)

  @decorate cacheable(cache: Cache, key: a, opts: [ttl: @ttl])
  def type(a)

  def type(a) when is_integer(a), do: :integer
  def type(a) when is_binary(a), do: :binary

  def type(_a), do: :something_else
end
```
In these cases, the compiler complains that `a` doesn't exist: 
```bash
MIX_ENV=test iex -S mix
Erlang/OTP 25 [erts-13.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]

Compiling 1 file (.ex)
warning: variable "a" does not exist and is being expanded to "a()", please use parentheses to remove the ambiguity or change the variable name
  lib/my_app/info.ex:9: MyApp.Info.type/1


== Compilation error in file lib/my_app/info.ex ==
** (CompileError) lib/my_app/info.ex:9: undefined function a/0 (expected MyApp.Info to define such a function or for it to be imported, but none are available)
```
The same happens if I remove the empty function head:
```elixir
defmodule MyApp.Info do
  @moduledoc false

  use Nebulex.Caching
  alias MyApp.Cache

  @ttl :timer.hours(1)

  @decorate cacheable(cache: Cache, key: a, opts: [ttl: @ttl])
  def type(a) when is_integer(a), do: :integer
  def type(a) when is_binary(a), do: :binary

  def type(_a), do: :something_else
end
```

To make it works (compile), I needed to either use the argument/variable for logging (as only removing the `_` would trigger a credo warning and consequently makes the CI pipeline fails):
```elixir
@decorate cacheable(cache: Cache, key: a, opts: [ttl: @ttl])
  def type(a)

  def type(a) when is_integer(a), do: :integer
  def type(a) when is_binary(a), do: :binary

  def type(a) do
     IO.inspect(a)
     :something_else
  end
```
or add a decorator to each clause:
```elixir
defmodule MyApp.Info do
  @moduledoc false

  use Nebulex.Caching
  alias MyApp.Cache

  @ttl :timer.hours(1)

  @decorate cacheable(cache: Cache, key: a, opts: [ttl: @ttl])
  def type(a) when is_integer(a), do: :integer

  @decorate cacheable(cache: Cache, key: a, opts: [ttl: @ttl])
  def type(a) when is_binary(a), do: :binary

  @decorate cacheable(cache: Cache, opts: [ttl: @ttl])
  def type(_a), do: :something_else
end
```
which is not recommended by the [docs](https://hexdocs.pm/nebulex/Nebulex.Caching.html#module-functions-with-multiple-clauses).

### Environment
* Operating system: **Ubuntu 22.04.1 LTS**
* Elixir & Erlang/OTP versions (elixir --version):
```bash
$ elixir --version
Erlang/OTP 25 [erts-13.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]

Elixir 1.14.0 (compiled with Erlang/OTP 23)
```
* Mix version:
```bash
$ mix --version
Erlang/OTP 25 [erts-13.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]

Mix 1.14.0 (compiled with Erlang/OTP 23)
```

**Comment by cabol** [comment]
Yeah, I was checking and the error comes from the `:decorator` library (Nebulex depends on it), and it is because the last function clause `def type(_a), do: :something_else` (because of the skipped underscored variable). We can see if perhaps we can do something about it, but in the meantime, I suggest maybe rewrite the function like this (a workaround):

```elixir
@decorate cacheable(cache: Cache, key: a, opts: [ttl: @ttl])
def type(a) do
  do_type(a)
end

defp do_type(a) when is_integer(a), do: :integer
defp do_type(a) when is_binary(a), do: :binary
defp do_type(_a), do: :something_else
```

That should work, I've tried it out. Unfortunately, there are some limitations when using decorators, but I will see if is there anything we can do about it. Thanks!

**Comment by cabol** [comment]
Since this is an issue related to the `:decorator` library itself, I will close it for now (perhaps in the future, we will explore if there is something that can be done in Nebulex to fix it).
