### ISSUE TITLE
Is there a good way to evict multiple caches at once by some conditions?

### ISSUE THREAD

**Issue by nallwhy** [cabol/nebulex#192]
When `update_org_default_value/2` is called, I want to evict all caches of `get_value_of_user/2`associated with the `org_id`.

```elixir
defmodule MyModule do
  @decorate cacheable(cache: MyCache, key: {__MODULE__, :get_value_of_user, [org_id, user_id]})
  def get_value_of_user(org_id, user_id) do
    ...
  end

  @decorate cache_put(cache: MyCache, key: ?)
  def update_org_default_value(org_id, default_value) do
    ...
  end
end
```

ex) when `update_org_default_value(1, true)` is called, caches below are evicted.

```elixir
{__MODULE__, :get_value_of_user, [1, 1]})
{__MODULE__, :get_value_of_user, [1, 2]})
{__MODULE__, :get_value_of_user, [1, 3]})
...
```

not below

```elixir
{__MODULE__, :get_value_of_user, [2, 4]})
{__MODULE__, :get_value_of_user, [3, 5]})
...
```

Can I do this with nebulex?

**Comment by cabol** [comment]
Hi!

You can evict a key or multiple keys with the decorators `cache_evict` or `cache_put` by means of:
- Option `keys:`, but you have to explicitly tell what keys you want to evict.
- You can also use `key_generator:` option, which allows you to write your own key generation; the `:key_generator` option can be used in all decorators.

Now, according to what you are trying to achieve perhaps the `:key_generator` may be more useful because I see you want to dynamically generate the keys to remove, don't you? Anyway, you can see more details and examples in the [Nebulex Caching Docs](https://hexdocs.pm/nebulex/Nebulex.Caching.html), let me know if that helps.

**Comment by nallwhy** [comment]
hm.. I don't think I understood it.
What I thought was evicting cache with a function like

```elixir
import Ex2ms



@decorate cacheable(cache: MyCache, key_condition: fn key -> key_condition(key, org_id) end)
def update_org_default_value(org_id, default_value) do
  ...
end

defp key_condition({__MODULE__, :get_value_of_user, [org_id, user_id]}, org_id) do
  true
end

defp key_condition(_key, _org_id) do
  false
end
```

**Comment by nallwhy** [comment]
or connect keys like

![image](https://user-images.githubusercontent.com/4961183/220220748-9deb9b0d-3e6e-4ce6-be1d-24e060116556.png)

**Comment by nallwhy** [comment]
Oh it's in the docs.
Sorry.

https://hexdocs.pm/nebulex/getting-started.html#fetch-all-entries-from-cache-matching-the-given-query

**Comment by cabol** [comment]
Unfortunately, you can't, at least not directly in the decorator, this is a more specific use case. However, there might be a workaround using the [`key_generator` option](https://hexdocs.pm/nebulex/Nebulex.Caching.html#module-the-key_generator-option).

```elixir
@decorate cache_evict(cache: MyCache, key_generator: CustomKeyGenerator)
def update_org_default_value(org_id, default_value) do
  ...
end
```

The key generator:

```elixir
defmodule CustomKeyGenerator do
  @behaviour Nebulex.Caching.KeyGenerator

  @impl true
  def generate(_module, :update_org_default_value, [org_id, default_value]) do
    # Here you can run the logic you need, it is not ideal because the idea is to return the keys you want to evict
    MyCache.delete_all(....) #=> your match-spec goes here

    # Return `nil` because you are already deleting the keys, so the decorator won't make any effect
    nil
  end
end
```

On the other hand, this makes me think of a new feature, I've created a new ticket for it, check it out: https://github.com/cabol/nebulex/issues/193

**Comment by nallwhy** [comment]
Cool! I'll try that.
Thanks!
