### ISSUE TITLE
Replicated adapter syncing during rolling deployment

### ISSUE THREAD

**Issue by benonymus** [cabol/nebulex#209]
Hey,

I am wondering about the replicated adapter syncing.

In the caveats in the docs it is mentioned that joining the cluster is expensive.
During a rolling deployment instances are updated 1 by 1.

Can it be expected that no data is lost during such a deployment with the replicated adapter?

As an example if we have 2 instances:
1. Instance 1 is updated 
2. Instance 1 starts to sync the cache from Instance 2
3. Will instance 2 wait with the shutdown until the cache is in sync?
4. Instance 2 is updated and sync back from instance 1 

Thank you

**Comment by benonymus** [comment]
Everything seems to be lost on deployment. I tried with 3 instances to give more time potentially for syncing, but it didn't help.

**Comment by cabol** [comment]
Hey!

> Can it be expected that no data is lost during such a deployment with the replicated adapter?

Unfortunately, that cannot be guaranteed. As you know, a deployment can be done in many different ways, so the cache can't be aware of that. The replicated cache tries to keep consistency across the "Erlang/Elixir Cluster", however, it doesn't guarantee "no data loss".

> 3. Will instance 2 wait with the shutdown until the cache is in sync?

No, it won't. When you shut down an instance, you are killing the cache too, the cache is not aware you are updating or shutting down the instance; it does a clean-up on termination ensuring the stopped cache leaves the cluster, but that's all (and this will happen only if you stop the app – like using `Application.stop(...)` or calling your release stop script `my_app stop`, like a graceful shutdown). So, maybe what is happening when you update instance 1, the sync-up process may have started, but instance 2 is immediately updated, then instance 1 is not able to finish the sync-up process (or maybe it happens so fast that the sync-up hasn't started yet), means, there is no data at that point in time.

If "cache data loss" is critical for you, I'd take a different approach. Currently, the cache runs within your app (same supervision tree) in the same instance. There may be other approaches (a bit more complex but more robust):
- "Cache Servers" topology – cache servers running outside your app (like a separate cache app), on a separate cluster, so they are not affected by your app deployments.
- "Redis Cache" – you could use the `NebulexRedisAdapter` and use Redis as a cache. This is usually the approach I take for more robust and complex scenarios. Here, you can leverage Redis features, like, cluster mode, persistency, sharding topology using Envoy proxy, etc.

Anyway, please let me know if that helps, I stay tuned!

**Comment by benonymus** [comment]
Hey thanks for confirming!

Would it be in vain to do the following:
Add a callback option to the replicated adapter that is called when the sync is complete, and have that callback be tied to the healthcheck of the app (set a value in a local cache or keep it in a genserver).
Now until that value is set to true the healthcheck on the new instance would fail and keep the deployment from moving forward.

I am experimenting with this on this fork: https://github.com/benonymus/nebulex/commit/2f6036cd500b6237e5358b99c06afdfed5cdf4e5

**Comment by benonymus** [comment]
We decided to use mnesia with https://github.com/sheharyarn/memento for the shared cache, thanks for the responses!

**Comment by cabol** [comment]
Alright, that makes sense. I will check your suggestion anyway. Also, it is planned for the replicated adapter to use Mnesia in the near future, so keep you posted. Thanks!

**Comment by dewetblomerus** [comment]
What about inserting a bogus value into the cache as part of the readiness check? Then, because it is blocking while the cache is being copied, K8s won't send traffic to the new node or shut down the old ones until the readiness check passes.

**Comment by cabol** [comment]
I'm not sure if I understand this correctly, but I'd say maybe that doesn't work. Imagine the scenario. You start `node1`, and there are some insertions. Then you start `node2`, at that moment `node2` starts the sync process to copy the data from `node1`. But during that time, the `node1` is shut down. Therefore, the sync process cannot be completed, and since there are no more nodes available to copy the data from, the cache starts empty. The challenge here is how `node2` knows that another node is copying data from it? The `node2` is locked, but it is not necessarily aware of the data copy. So, how does `node2` know it has to "_insert a fake key/value_" because of the sync process? That is the part I don't understand from your proposal; maybe I'm missing something.
