### ISSUE TITLE
Bug on Local adapter when using `delete_all` and keys are nested tuples: not a valid match specification

### ISSUE THREAD

**Issue by lurodrigo** [cabol/nebulex#211]
It looks like the match spec being generated by the Local adapter when using `delete_all({:in, [term]})` fails when keys are nested tuples. The minimal reproducible example I've found is: 

```elixir
Cache.delete_all(
  {:in, [
    {nil, {nil, nil}}, 
    nil]}
)
```

You get: 

```
** (ArgumentError) errors were found at the given arguments:

  * 2nd argument: not a valid match specification

    (stdlib 4.3.1.2) :ets.internal_select_delete(#Reference<0.3195127284.3105226753.258702>, [{{:entry, :"$1", :"$2", :"$3", :"$4"}, [{:orelse, {:==, :"$1", {{nil, {nil, nil}}}}, {:==, :"$1", nil}}], [true]}])
    (stdlib 4.3.1.2) ets.erl:401: :ets.select_delete/2
    (nebulex 2.5.2) lib/nebulex/adapters/local.ex:880: Nebulex.Adapters.Local.do_delete_all/7
    (nebulex 2.5.2) lib/nebulex/adapters/local.ex:656: anonymous fn/4 in Nebulex.Adapters.Local.do_execute/4
    (elixir 1.14.5) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (nebulex 2.5.2) lib/nebulex/adapters/local.ex:633: anonymous fn/5 in Nebulex.Adapters.Local.execute/4
```

The list must have at least 2 elements (the implementation for a single element defers to `delete`). By looking at the code, it looks like tuples are wrapped. I don't know much about match specs but maybe we should wrap recursively? But that would have performance implications... Anyway, for the time being I'll use a slightly different format.

**Comment by cabol** [comment]
Hey, thanks for catching this bug! I've pushed a fix already, it is on the master branch, please try it out and let me know how it goes, thanks!

**Comment by cabol** [comment]
@lurodrigo any feedback here?
