### ISSUE TITLE
is allocated_memory param global on per node when using Nebulex.Adapters.Partitioned with :shards

### ISSUE THREAD

**Issue by juancgalvis** [cabol/nebulex#213]
Hello,

I am new using this cache aproach, and I have a question related to allocated_memory, I will have many nodes and I want that each one have some of all data, I don`t need data replicates across all nodes, so I will use Nebulex.Adapters.Partitioned adapter with :shards, My question: is allocated_memory param global or per node?

Thank you!

**Comment by cabol** [comment]
Hi! The `allocated_memory` is per node since it is a [configuration option for the local adapter](https://hexdocs.pm/nebulex/Nebulex.Adapters.Local.html#module-options) used underneath.

Thanks!

**Comment by cabol** [comment]
Closing this issue, but feel free to re-open it if you have more doubts or comments about it. Thanks!
