### ISSUE TITLE
Regression on decorated functions and Elixir 1.16

### ISSUE THREAD

**Issue by GRoguelon** [cabol/nebulex#216]
Hi,

I've updated few applications to Elixir 1.16.0 and found an issue with Nebulex and decorated functions.

If you take the following example:
```elixir
@decorate cacheable(
            cache: NebulexDecoratedKeys.Cache,
            keys: [name],
            opts: [ttl: :timer.minutes(15)]
          )
def hello(name) do
  "Hello, #{name}!"
end
```

The option `keys` is not respected. The first time you call the function, the return value is as expected but if you call a second time the function with a different `name` , it will return the previous value instead of the correct one.

I've made a [minimal project](https://github.com/GRoguelon/nebulex_decorated_keys) to demonstrate the issue. The instructions to reproduce the bug are in the `README.md`.

**Comment by cabol** [comment]
Hi.

Keep in mind the option `:keys` is not available for the `cacheable` decorator (it is only allowed on `cache_evict` and `cache_put` decorators), then, it is being ignored in your example. You have to use the option `:key` instead. You can check the docs: https://hexdocs.pm/nebulex/Nebulex.Caching.Decorators.html#cacheable/3-options.

**Comment by GRoguelon** [comment]
HI @cabol,

I just read the document and I wrongly used `keys` for months. Weird though that it breaks only now with a new version of Elixir.

I will adjust my code, thank you for your prompt reply and thank you for this great package, very handy!

**Comment by cabol** [comment]
Hi @GRoguelon !!

> I just read the document and I wrongly used keys for months. Weird though that it breaks only now with a new version of Elixir.

Yeah, it is weird, will take a look.

> I will adjust my code, thank you for your prompt reply and thank you for this great package, very handy!

Thanks 🙇
