### ISSUE TITLE
`Multilevel` inclusive cache doesn't duplicate entries backwards on `get_all/2`

### ISSUE THREAD

**Issue by renatoaguiar** [cabol/nebulex#219]
In a `Multilevel` cache configured to use `:inclusive` model, keys should be copied to previous levels on get operations, but that doesn't happen when using `get_all/2`.

Here is a test case showing the problem:

```
diff --git a/test/nebulex/adapters/multilevel_inclusive_test.exs b/test/nebulex/adapters/multilevel_inclusive_test.exs
index 810455d..d1c2f36 100644
--- a/test/nebulex/adapters/multilevel_inclusive_test.exs
+++ b/test/nebulex/adapters/multilevel_inclusive_test.exs
@@ -103,6 +103,31 @@ defmodule Nebulex.Adapters.MultilevelInclusiveTest do
       refute Multilevel.get(:b, level: 2)
       refute Multilevel.get(:b, level: 3)
     end
+
+    test "get_all" do
+      :ok = Process.sleep(2000)
+      :ok = Multilevel.put(1, 1, level: 1)
+      :ok = Multilevel.put(2, 2, level: 2)
+      :ok = Multilevel.put(3, 3, level: 3)
+
+      assert Multilevel.get_all([1]) == %{1 => 1}
+      refute Multilevel.get(1, level: 2)
+      refute Multilevel.get(1, level: 3)
+
+      assert Multilevel.get_all([1, 2]) == %{1 => 1, 2 => 2}
+      assert Multilevel.get(2, level: 1) == 2
+      assert Multilevel.get(2, level: 2) == 2
+      refute Multilevel.get(2, level: 3)
+
+      assert Multilevel.get(3, level: 3) == 3
+      refute Multilevel.get(3, level: 1)
+      refute Multilevel.get(3, level: 2)
+
+      assert Multilevel.get_all([1, 2, 3]) == %{1 => 1, 2 => 2, 3 => 3}
+      assert Multilevel.get(3, level: 1) == 3
+      assert Multilevel.get(3, level: 2) == 3
+      assert Multilevel.get(3, level: 2) == 3
+    end
   end
 
   describe "distributed levels" do
```

It looks like this is a regression introduced long ago with https://github.com/cabol/nebulex/commit/faff154dfd38758d736ab04dcd9e87394b45a77d. The above test passes with that commit reverted.

**Comment by cabol** [comment]
Hi! Good catch! I'll check it out.

**Comment by cabol** [comment]
I've pushed a fix for this. However, it is important to keep some things in mind. It was documented that the replication (or duplicate) of the entry was only for the `get` callback, but I understand it should happen on the `get_all` callback as well, to be consistent. The challenge is replicating multiple keys while keeping their TTLs. Therefore, the `get_all` is translated into multiple `get` calls underneath (as it was implemented previously), but this will affect the performance as is described in issue #139. To address it in a better way, this only happens on `:inclusive` mode and I added an extra option `:replicate` (only valid for the `get_all` callback) to be able to skip the replication if we want to (by default replication is enabled).

Anyway, please try it out and let me know your comments or inquiries.

**Comment by cabol** [comment]
@renatoaguiar I'm closing this for now, but feel free to reopen it if you find an issue, unexpected behavior, etc.
