### ISSUE TITLE
Adapter for Memcached

### ISSUE THREAD

**Issue by cabol** [cabol/nebulex#22]

**Comment by vasuadari** [comment]
I would like to work on this. Has someone picked this up already?

**Comment by cabol** [comment]
@vasuadari not yet, I'm glad you want to work on it :), so feel free to do it. I've made a bit of progress [nebulex_memcached_adapter](https://github.com/cabol/nebulex_memcached_adapter), but I haven't been able to continue. So again, feel free to start your own repo or work on the existing one (it's your call!). Any doubt please let me know. Thanks and I stay tuned!

**Comment by vasuadari** [comment]
> not yet, I'm glad you want to work on it :), so feel free to do it.

Thanks

> Any doubt please let me know.

Sure 👍

**Comment by vasuadari** [comment]
@cabol I have created a new repo <a href="https://github.com/vasuadari/nebulex_memcached_adapter" target="_blank">here</a>. Except for `Nebulex.Cache.Queryable` every other functions are supported however there is one catch with `get_many` implementation for `memcached`. Although `memcached` provides `multi_get` call unlike `redis` it doesn't return nil for missing keys which is the problem. As a workaround i'm doing multiple fetch :(.

Please check the repo and let me know about your views.

**Comment by cabol** [comment]
@vasuadari looks very good so far, nice work 👍

**Comment by vasuadari** [comment]
@cabol
> I'll update Nebulex pointing to the new Memcached adapter 

Thanks :)

> Once you have a stable release, we have to provide the distributed part on top of that, so let me know when it is ready!

Sure, i'll spend some time on that.

> BTW, try to add CI with test, coverage, check style, etc.

Definitely i was planning to set it up but couldn't find time. Will set it up soon.

> Again, thanks a lot for your contribution and let me know if you need something from my side!!

Sure 👍

**Comment by cabol** [comment]
Since there is significant work already done for this adapter and a different repo [nebulex_memcached_adapter](https://github.com/vasuadari/nebulex_memcached_adapter), any issue, improvement, suggestion, etc., regarding to Memcached adapter should be reported in there.

Thank you so much @vasuadari for your contribution :) !!
