### ISSUE TITLE
Fix compatibility with Elixir 1.15 and 1.16

### ISSUE THREAD

**Issue by cabol** [cabol/nebulex#220]
**NOTE:** This should fix #218

**Comment by tomtaylor** [comment]
Brilliant, thanks! It would be great to get a release cut with this fix. It's quite a dangerous bug and wonder if there's a way of ensuring that people on a previous release who upgrade to Elixir 1.16 don't get stung?

**Comment by cabol** [comment]
Release published!

**Comment by tomtaylor** [comment]
Thank you!
