### ISSUE TITLE
Cache.all(nil, return: :value) with a partitioned cache gives incorrect results

### ISSUE THREAD

**Issue by jweinkam** [cabol/nebulex#228]
1. Create a Partitioned cache MyCache
2. Store the following in the cache
  - MyCache.put(:key1, 1)
  - MyCache.put(:key2, 2)
  - MyCache.put(:key3, [3, 4])
3. MyCache.all(nil, return: :value)

Expected results
[[3, 4], 2, 1]

Actual results
[3, 4, 2, 1]

The following change at line 580 of lib/nebulex/adapters/partitioned.ex fixes the issue
```diff
  @impl true
  defspan execute(adapter_meta, operation, query, opts) do
    reducer =
      case operation do
-        :all -> &List.flatten/1
+        :all -> &Enum.flat_map(&1, fn item -> item end)
        _ -> &Enum.sum/1
      end

    adapter_meta.task_sup
    |> RPC.multi_call(
      Cluster.get_nodes(adapter_meta.name),
      __MODULE__,
      :with_dynamic_cache,
      [adapter_meta, operation, [query, opts]],
      opts
    )
    |> handle_rpc_multi_call(operation, reducer)
  end
```

**Comment by cabol** [comment]
@jweinkam perhaps you can open a PR with the fix? Thanks 🙏 !!
