### ISSUE TITLE
Cache Failing to Start on Production

### ISSUE THREAD

**Issue by zacksiri** [cabol/nebulex#26]
I'm getting the error as referenced here https://github.com/cabol/shards/issues/41

It's working fine in development, however in production it's failing, I'm using distillery to make my production build.

**Comment by cabol** [comment]
@zacksiri I think it is due to `distillery` (https://github.com/bitwalker/distillery/issues/55).

Try to add `:shards` and `:ex_shards` to your included apps in your `mix.exs`, like so:

```elixir
def application do
    [
      extra_applications: [:logger],
      mod: {Blog.Application, []},
      included_applications: [:shards, :ex_shards]
    ]
  end
```

> NOTE: For further releases of Nebulex (> `1.0.0-rc.3`), `:ex_shards` was removed, Nebulex now uses `:shards` directly, so you have to include only `:shards` to `included_applications` – Check out master branch; Release `1.0.0` will be launched soon :).

**Comment by zacksiri** [comment]
I upgraded to master and added `:shards` seems to be working thank you!

**Comment by zdenal** [comment]
@cabol ... could be this added also into [getting started](https://hexdocs.pm/nebulex/getting-started.html) and [Nebulex](https://hexdocs.pm/nebulex/Nebulex.html) documentations. I have solving today same issue which was raise only on staging/production release and this helped.

**Comment by cabol** [comment]
@zdenal sure, let me try to find a good place to add it!
