### ISSUE TITLE
has_key?/1 does not respect ttl

### ISSUE THREAD

**Issue by nsweeting** [cabol/nebulex#33]
### Environment

Elixir version (elixir -v): Elixir 1.7.3 (compiled with Erlang/OTP 21)
Nebulex version (mix deps): 1.0.0
Operating system: Ubuntu 18.04

### Expected behavior
Using `has_key?/1` on a key that was set with a ttl should return `false` when the ttl has expired. 

### Actual behavior

```elixir
iex> Cache.set(:foo, 1, ttl: 0)
1
iex> Cache.get(:foo)
nil
```
```elixir
iex> Cache.set(:foo, 1, ttl: 0)
1
iex> Cache.has_key?(:foo)
true
```

**Comment by cabol** [comment]
@nsweeting good catch! It is fixed now (master branch). Please check it out again and feel free to re-open it if the problem persist.
