### ISSUE TITLE
Will nebulex support replicating cache partitions?

### ISSUE THREAD

**Issue by queer** [cabol/nebulex#47]
I'm sorry if this has been asked before; I couldn't find it with a quick search.

My question is pretty much just the title. I have a real use-case for wanting to be able to replicate partitions - as a full replication à la #15 would require too much RAM usage - and I also don't have the ~~brain power~~ time/knowledge to write a partition replicator that I would have any confidence in. I'm also somewhat curious if this effect can be created by just running two `Dist` caches per node - I feel like it might work but also might just double the data being stored on each node with no real gain.

**Comment by queer** [comment]
Never mind; I think my problem would be more suited to something like `riak_core`.

**Comment by cabol** [comment]
@queer about your question, yes, Nebulex will eventually implement [replicated topology](https://docs.oracle.com/cd/E16459_01/coh.350/e14510/replicatedcacheservice.htm) via #15 (adapter).

>  I have a real use-case for wanting to be able to replicate partitions - as a full replication à la #15 would require too much RAM usage

Indeed, actually memory consumption is one of the downsides of the replicated topology.

> and I also don't have the brain power time/knowledge to write a partition replicator that I would have any confidence in. I'm also somewhat curious if this effect can be created by just running two Dist caches per node - I feel like it might work but also might just double the data being stored on each node with no real gain.

NP, thanks for the interest :)!! Replicated topology impl is in progress now (we hope to have a first draft very soon), and I'm thinking to implement a `mnesia` adapter, which will give us the ability to setup different topologies, not only full-replicated but also partitioned topology with better failover mechanism using replicas (via `mnesia` fragments maybe?).

> Never mind; I think my problem would be more suited to something like `riak_core`

Indeed, `riak_core` is another option to implement it – actually, it would be nice to have an adapter using `riak_core` :)

**Comment by queer** [comment]
As it turns out, I've come full-circle back to Nebulex, as I've not been able to get `riak_core` working :sweat_smile:

**Comment by cabol** [comment]
:smile: Yeah, get `riak_core` working may be a bit tricky. If you want to continue with `riak_core`, perhaps I have a couple of projects that might help: [erlbus v0.1.0](https://github.com/cabol/erlbus/tree/0.1.0) and [west](https://github.com/cabol/west). But anyways, the `mnesia` adapter is in progress, I hope to publish a draft version very soon.
