### ISSUE TITLE
Ability to "get or set" a key

### ISSUE THREAD

**Issue by nsweeting** [cabol/nebulex#49]
A common caching scenario is to attempt to get a key, and if it doesnt exist, set it. This could quite easily be implemented with something like the following:

```elixir
  def get_or_set(key, function, opts \\ []) do
    transaction(fn ->
      with nil <- get(key, opts) do
        set(key, function.(), opts)
      end
    end)
  end
```

```elixir
MyCache.get_or_set(:foo, fn -> :bar end)
```

If this is something of interest, I could look at implementing it soon.

**Comment by cabol** [comment]
@nsweeting I like the idea! And yes, please implement it, and send the PR!!

I would suggest two things:
1) For the transaction, pass the `keys` option to lock only that specific key (not the whole cache).
2) For the second argument, allow receiving a value too (`function_or_value`)

Something like:

```elixir
def get_or_set(key, function_or_value, opts \\ []) when is_function(function_or_value) do
  get_or_set(key, function_or_value.(), opts)
end

def get_or_set(key, function_or_value, opts \\ []) do
  transaction(fn ->
    with nil <- get(key, opts) do
      set(key, function_or_value, opts)
    end
  end, keys: [key])
end
```

I like the idea because is useful and easy to implement. Looking forward to your PR :) !!!

> Just to keep it in mind, you only have o modify [Nebulex.Cache.Object](https://github.com/cabol/nebulex/blob/master/lib/nebulex/cache/object.ex) adding the implementation, and then [Nebulex.Cache](https://github.com/cabol/nebulex/blob/master/lib/nebulex/cache.ex) to add the new function within the `using` macro and also de callback (with doc).

**Comment by cabol** [comment]
You know, actually, I'd rather make it simpler, just receiving the value, like so:

```elixir
def get_or_set(key, value, opts \\ []) do
  transaction(fn ->
    with nil <- get(key, opts) do
      set(key, value, opts)
    end
  end, keys: [key])
end
```

And you can execute the fun before to call it:

```elixir
get_or_set("foo", fun.(), opts)
```

What do you think?

**Comment by nsweeting** [comment]
Actually - my main reason for doing something like the above was to avoid database calls. If its able to receive a function as well -  it can be lazily evaluated - only hitting the db on key miss.

I think passing either a function or value could work though. The function should only be run on key miss though - as it may be a heavier operation.

**Comment by cabol** [comment]
Ok I see, agreed, let's keep the function then, I'm not sure about the value now :P ... Based on what you say, which makes a lot of sense, I don't know if we should support the value as well, I think the function is generic enough, it would act as a "fallback function". So your original idea is OK, just adding the option `keys: [key]`.

On the other hand, based on your original reason:

> Actually - my main reason for doing something like the above was to avoid database calls. If its able to receive a function as well - it can be lazily evaluated - only hitting the db on key miss.

Why if you use the [cacheable](https://github.com/cabol/nebulex/blob/master/lib/nebulex/caching.ex#L60-L92) feature here?

**Comment by nsweeting** [comment]
Actually - wasnt aware of the cacheable feature! For sure useful.

Still worth implementing? For those that might have a slight aversion to custom macros :smile:

**Comment by cabol** [comment]
Yeah, I think still worth, let's do it!
