### ISSUE TITLE
Add matching option on returned result to Nebulex.Caching

### ISSUE THREAD

**Issue by polmiro** [cabol/nebulex#55]
There is a use that I believe is fairly common that I do not think fits in the `Nebulex.Caching` macro DSL.

Sometimes one wants to conditionally cache a value based on the result of the underlying function logic. This is easy to achieve by using the lower-level APIs `Cache.get` and `Cache.set` but it is fairly verbose and repeatable. Also, I was really enjoying the `Nebulex.Caching` DSL.

In my specific use case, I have a cache-through layer in front of a REST API and I only want to cache the results when the REST query underneath succeeds. Sometimes there are transient error responses or short periods of time where this API is down.

I added an optional function argument called `match` (for lack of better naming at the moment) to `defcacheable` that receives the result of the logic and returns a boolean value. Based on that, the value will be cached or not cached. For example:
```elixir
defcacheable get_user(id), cache: Cache, key: {User, id}, match: &match?/1 do
  Tesla.get("users/#{id}")
end

defcacheable get_users(id), cache: Cache, key: {User, :list}, match: &match?/1 do
  Tesla.get("users")
end

# Successful requests will be cached
def match?({:ok, _}), do: true
# Failed requests will not be cached
def match?(_), do: true
```

If you think this would be worth adding I would be happy to write a PR, I already have something I can base it off. It is fairly straight-forward.

By the way, thanks for such a great library, cheers 🙇 !

**Comment by cabol** [comment]
Hey @polmiro, that looks like a very nice feature!

> If you think this would be worth adding I would be happy to write a PR, I already have something I can base it off. It is fairly straight-forward.

Absolutely it's worth it, please send the PR! Again, this would be a very nice and useful feature, thanks!

> By the way, thanks for such a great library

Thank you so much, glad to hear that!

**Comment by polmiro** [comment]
Closing in favor of the PR then :)
