### ISSUE TITLE
Pre Expire Hook

### ISSUE THREAD

**Issue by eamonpenland** [cabol/nebulex#57]
Im trying to implement a delayed queue. I was thinking I could maybe add items into the cache with a ttl, and before expiration get a pre-expire or pre-evict callback to do what I need to do with the items. It doesn't appear like this is supported. Any ideas?

**Comment by cabol** [comment]
Yeah, unfortunately that's not supported for the current adapters, it is very specific and also depends on the cache and adapter implementation. There might be caches that gives you that information via events (subscriptions), and normally they tell you when a key expires, but not X period of time before it expires. So, for this specific use case you have to implement something at application level. For example, using a pre-hook, you can pattern-match the `get`s with the key you want, and check if that key is gonna expire soon or not and then apply your custom logic, but of course, it is a logic that will be performed every time you do a `get`. For more info, you can check this section about [pre/post hooks](https://hexdocs.pm/nebulex/hooks.html)
