### ISSUE TITLE
Load/Stress Tests

### ISSUE THREAD

**Issue by cabol** [cabol/nebulex#6]
Make load/stress tests for Nebulex, including the local generational cache and distributed cache either. This can be done in a separated repo (e.g.: `nebulex_bench`) and documenting results in a blog post maybe.

**Comment by fire** [comment]
Tried using benchfella to benchmark the cache.

I was wondering why this 500,000 does not change on a laptop 2 cores or a desktop 4+ cores.

https://github.com/fire/database_cache_benchmark/blob/master/bench/database_bench.exs#L13

```
## BasicBench
benchmark name iterations   average time
cached select      500000   5.12 µs/op
```

**Comment by fire** [comment]
This is using cockroachdb, but it should be compatible with postgresql.

**Comment by cabol** [comment]
@fire thanks for the bench! I had added a [simple bench to Nebulex](https://github.com/cabol/nebulex#benchmarks) using the same library benchfella, but only for local and distributed adapter, without Ecto, so it is an interesting and complementary bench test to Nebulex.

On other hand, I don't know much about benchfella, at least not in terms of its implementation, so I'm not sure if benchfella is suitable to do load tests, spawning a bunch of processes to hit the cache and then be able to measure not only latency but also throughput (how many writes and reads per second is able to handle). For example, I did some load tests for [shards](https://github.com/cabol/shards) using [basho_bench](https://github.com/basho/basho_bench), and that is precisly what I want to be able to do – check out this [blog post](http://cabol.github.io/posts/2016/04/14/sharding-support-for-ets.html/), the performance tests section.

**Comment by fire** [comment]
Are you familiar with using basho_bench to test ecto (with postgresql / cockroachdb) driver?

**Comment by cabol** [comment]
I'm familiar with basho_bench, but the tricky part is to integrate Elixir and Ecto within the project, since basho_bench doesn't works with rebar3 (AFAIK), then you cannot use the [rebar3_elixir_compile](https://github.com/barrel-db/rebar3_elixir_compile) plugin, and that makes it more difficult. However, I think it would be easy to add rebar3, and I'd also remove unnecessary dependencies, try to prune the project a bit, anyways, I'll try to do it.

**Comment by fire** [comment]
There's two parts to my benchmark. A)The ecto schema / ecto caching and B) the phoenix json api. 

As far as I know, only the ecto schema part is used in the benchfella benchmark. So I can delete the phoenix framework, but I would rather made it work because one of my goals is to either use thrift (elixir-thrift) or phoenix to provide access to the ecto database / caching.

**Comment by cabol** [comment]
Absolutely, that's fine, you should keep everything that make sense to you. When I said "*try to prune the project a bit*" I was referring to basho_bench, because it brings with a lot of dependencies, which are not necessary to do the test. What I'd like to do is try to use basho_bench against Nebulex, I'll try to make it soon.

**Comment by fire** [comment]
Are you using a fork of basho_bench? I could look at it after work hours.

**Comment by cabol** [comment]
Yes I use a [fork](https://github.com/cabol/basho_bench) but it is outdated and it hasn't Nebulex included yet, I used that fork to test [shards](https://github.com/cabol/shards)

**Comment by fire** [comment]
Have you looked at basho bench lately? There are compatibility fixes I believe to erlang 20 or at least there's a riak working group now.

**Comment by cabol** [comment]
@fire no, but I will, it is a very good news, I'll take a look at it and try to do this load testing soon. Thanks :) !!

**Comment by fire** [comment]
If you had problems, this is the one that has erlang 19 compatibility. https://github.com/mrallen1/basho_bench/blob/mra-rebar3/README.org#quick-start

**Comment by fire** [comment]
Ping!

**Comment by cabol** [comment]
Hi @fire, my plan is start work on this issue this week (actually is the next one in my list), and of course I'll start checking out the link you sent me, as soon as I have some result I'll let you know. BTW, have you tried it out already?

**Comment by fire** [comment]
Was able to build it in Elixir and erlang 20, but didn't find time understanding how the drivers worked. That's where I stopped.

**Comment by cabol** [comment]
Ok, basically you have to provide two things to `basho_bench`:

1) As you mentioned, the driver, so in the `src` you can create a module like this:

```erlang
-module(basho_bench_nebulex).

-export([
  new/1,
  run/4
]).

-define(nbx_cache, 'Elixir.NbxCache').

new(_State) ->
  {ok, #{}}.

run(get, KeyGen, _ValueGen, State) ->
  Key = KeyGen(),
  _ = ?nbx_cache:get(Key),
  {ok, State};

run(put, KeyGen, ValueGen, State) ->
  ?nbx_cache:set(KeyGen(), ValueGen()),
  {ok, State}.
```

In this driver we are testing two operations, `get` and `set`, and the `run/4` function is executed depending on you config file.

2) The config file, so in the folder `examples` we can add out config file `basho_bench_nebulex.config`:

```erlang
{mode, max}.

{duration, 5}.

{concurrent, 8}.

{driver, basho_bench_driver_shards}.

{operations, [{put, 1}, {get, 1}]}.

{key_generator, {int_to_bin_bigendian, {uniform_int, 1000}}}.

{value_generator, {fixed_bin, 100000}}.
```

See that `{operations, [{put, 1}, {get, 1}]}` match with the `run/4` functions within the driver.

Now, the tricky part is, we have to create an elixir app for the Nebulex cache (`NbxCache`), and in order to be able to compile `nebulex` dep and our Cache `NbxCache` within the `basho_bench` project we need to use the `rebar3_elixir_compile` plugin.

I was able to compile `basho_bench` using rebar3 and with OTP 20, but now I'm struggling with the `rebar3_elixir_compile` plugin, for some reason the dependencies are not included in the escript so it fails. So I'll continue working on this and I'll let you know any progress. Now, if you can try as well that would be great, and let me know any issue or progress :) !!

**Comment by fire** [comment]
When I do a iex --werl -S mix run inside of https://github.com/fire/database_cache_benchmark I'm able to access the basho_bench functions.

Inside of the elixir shell I the ability to use both ecto and basho_bench. I'm not sure what do though.

**Comment by fire** [comment]
```
# Windows BASH or Linux
iex -S mix
:basho_bench.start()
:basho_bench.setup_benchmark([])
:basho_bench.run_benchmark(['./src/basho_bench_nebulex.config'])
```

Seems to work, but it crashes on `{driver, basho_bench_driver_shards}.`

**Comment by fire** [comment]
Added https://github.com/fire/database_cache_benchmark/blob/master/src/basho_bench_driver_shards.erl but still failing:

```
:basho_bench.start()
:basho_bench.setup_benchmark([])
:basho_bench.run_benchmark(['./src/basho_bench_nebulex.config'])
iex(4)> :basho_bench.run_benchmark(['./src/basho_bench_nebulex.config'])
12:39:49.792 [info] No dimension available for key generator: {int_to_bin_bigendian,{uniform_int,1000}}
12:39:49.796 [debug] Supervisor basho_bench_run_sup started basho_bench_duration:start_link() at pid <0.414.0>
12:39:49.845 [info] module=basho_bench_stats_writer_csv event=start stats_sink=csv
12:39:49.846 [debug] Supervisor basho_bench_run_sup started basho_bench_stats:start_link() at pid <0.415.0>
12:39:49.856 [info] Random source: calling crypto:strong_rand_bytes(100663296) (override with the 'value_generator_source_size' config option
12:39:51.926 [info] Random source: finished crypto:strong_rand_bytes(100663296)
12:39:51.931 [error] Failed to initialize driver basho_bench_driver_shards: {'EXIT',{badarg,[{ets,lookup,[xyz,state],[]},{shards_state,get,1,[{file,"/mnt/g/database_cache_benchmark/deps/shards/src/shards_state.erl"},{line,166}]},{basho_bench_driver_shards,new,1,[{file,"src/basho_bench_driver_shards.erl"},{line,9}]},{basho_bench_worker,worker_idle_loop,1,[{file,"/mnt/g/database_cache_benchmark/deps/basho_bench/src/basho_bench_worker.erl"},{line,229}]}]}}
12:39:51.931 [error] CRASH REPORT Process <0.419.0> with 0 neighbours exited with reason: {init_driver_failed,{'EXIT',{badarg,[{ets,lookup,[xyz,state],[]},{shards_state,get,1,[{file,"/mnt/g/database_cache_benchmark/deps/shards/src/shards_state.erl"},{line,166}]},{basho_bench_driver_shards,new,1,[{file,"src/basho_bench_driver_shards.erl"},{line,9}]},{basho_bench_worker,worker_idle_loop,1,[{file,"/mnt/g/database_cache_benchmark/deps/basho_bench/src/basho_bench_worker.erl"},{line,229}]}]}}} in basho_bench_worker:init/1 line 152
12:39:51.932 [error] Supervisor basho_bench_worker_sup had child basho_bench_worker_1 started with basho_bench_worker:start_link(basho_bench_worker_1, {single_worker,1,1}, []) at undefined exit with reason {init_driver_failed,{'EXIT',{badarg,[{ets,lookup,[xyz,state],[]},{shards_state,get,1,[{file,"/mnt/g/database_cache_benchmark/deps/shards/src/shards_state.erl"},{line,166}]},{basho_bench_driver_shards,new,1,[{file,"src/basho_bench_driver_shards.erl"},{line,9}]},{basho_bench_worker,worker_idle_loop,1,[{file,"/mnt/g/database_cache_benchmark/deps/basho_bench/src/basho_bench_worker.erl"},{line,229}]}]}}} in context start_error
** (exit) exited in: :gen_server.call({:global, :basho_bench_stats}, :run)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (stdlib) gen_server.erl:206: :gen_server.call/2
    (basho_bench) /mnt/g/database_cache_benchmark/deps/basho_bench/src/basho_bench.erl:98: :basho_bench.run_benchmark/1
```

**Comment by fire** [comment]
Loading https://github.com/fire/database_cache_benchmark:

```
# Windows BASH or Linux
iex -S mix
:basho_bench.start()
:basho_bench.setup_benchmark([])
:basho_bench.run_benchmark(['./src/basho_bench_nebulex.config'])
```

Will insert and fetch random uuids. 

How do you use  key_gen and value_gen in `def run(:put, key_gen, value_gen, state)` ?

**Comment by fire** [comment]
https://github.com/fire/database_cache_benchmark/blob/master/lib/basho_bench/basho_bench_nebulex_driver.ex is the nebulex driver written in Elixir.

**Comment by fire** [comment]
https://github.com/fire/database_cache_benchmark/commit/eca59d277904b88d36b65a112ec6fc9bde01709e Has my last work on trying to get uuid_v4 generation.

Reminder:

```
# Setup Postgresql / Cockroachdb config
:basho_bench.start()
:basho_bench.setup_benchmark([])
:basho_bench.run_benchmark(['./src/basho_bench_nebulex.config'])
```

**Comment by fire** [comment]
Error log:

```
iex(4)> :basho_bench.run_benchmark15:10:01.647 [debug] Lager installed handler lager_backend_throttle into lager_event

15:10:01.691 [info] No dimension available for key generator: uuid_v4
15:10:01.696 [debug] Supervisor basho_bench_run_sup started basho_bench_duration:start_link() at pid <0.421.0>
15:10:01.741 [info] module=basho_bench_stats_writer_csv event=start stats_sink=csv
15:10:01.742 [debug] Supervisor basho_bench_run_sup started basho_bench_stats:start_link() at pid <0.422.0>
15:10:01.749 [error] CRASH REPORT Process <0.426.0> with 0 neighbours crashed with reason: no function clause matching basho_bench_worker:init_generators(false, uuid_v4, 1, basho_bench_keygen) line 406
15:10:01.750 [error] Supervisor basho_bench_worker_sup had child basho_bench_worker_1 started with basho_bench_worker:start_link(basho_bench_worker_1, {single_worker,1,1}, []) at undefined exit with reason no function clause matching basho_bench_worker:init_generators(false, uuid_v4, 1, basho_bench_keygen) line 406 in context start_error
15:10:01.750 [error] Supervisor basho_bench_run_sup had child basho_bench_worker_sup started with basho_bench_worker_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,basho_bench_worker_1,{function_clause,[{basho_bench_worker,init_generators,[false,uuid_v4,1,basho_bench_keygen],[{file,"/mnt/g/database_cache_benchmark/deps/basho_bench/src/basho_bench_worker.erl"},{line,406}]},{basho_bench_worker,add_generators,1,[{file,"/mnt/g/database_cache_benchmark/deps/basho_bench/src/basho_bench_worker.erl"},{line,399}]},{basho_bench_worker,init,1,[{file,"/mnt/g/database_cache_benchmark/deps/basho_bench/src/basho_bench_worker.erl"},{line,...}]},...]}}} in context start_error
15:10:01.762 [warning] No data for op: {put,put}
15:10:01.762 [warning] No data for op: {get,get}
15:10:01.763 [info] No Errors.
15:10:01.763 [info] module=basho_bench_stats_writer_csv event=stop stats_sink=csv
** (exit) exited in: :gen_server.call({:global, :basho_bench_stats}, :run)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (stdlib) gen_server.erl:206: :gen_server.call/2
    (basho_bench) /mnt/g/database_cache_benchmark/deps/basho_bench/src/basho_bench.erl:98: :basho_bench.run_benchmark/1
```

**Comment by cabol** [comment]
Hi @fire, well actually you did a good progress, you took other approach (which I like it), instead of add `nebulex` and the cache to `basho_bench`, you added `basho_bench` as dependency of your elixir bench project, so I'll work on that, I'll try to reproduce the error you got, and try to move forward – BTW Thanks :) !!

**Comment by cabol** [comment]
@fire good news, I was able to run the basho_bench tests with your repo (database_cache_benchmark), I found some issues:

1) This line: https://github.com/fire/database_cache_benchmark/blob/master/src/basho_bench_nebulex.config#L11

Replace `{key_generator, uuid_v4}.` by `{key_generator, {int_to_bin_bigendian, {uniform_int, 1000}}}.`

2) There are some errors here: https://github.com/fire/database_cache_benchmark/blob/master/lib/basho_bench/basho_bench_nebulex_driver.ex – change the `ok` by `:ok`

It would be something like:

```elixir
defmodule BashoBench.Nebulex.Driver do
  def new(_state) do
    {:ok, {}}
  end

  def run(:put, key_gen, value_gen, state) do
    {:ok, _schema} = Hello.World.changeset(%Hello.World{}, %{id: key_gen.(), random_number: value_gen.()})
    |>  Hello.CacheableRepo.insert
    {:ok, state}
  end

  def run(:get, key_gen, value_gen, state) do
   _ = Hello.CacheableRepo.get(Hello.World, key_gen.())
    {:ok, state}
  end
end
```

Try that and let me know if it works for you, but I was able to run load tests against Nebulex finally, thanks to your help :) !!! I got with a humble machine (Mac OSX Sierra, Dual Core, 4 GB) about ~150K ops/seg, which is great!!

Well, try to run your test and let me know how it goes!

**Comment by fire** [comment]
Nebulex ran on my machine but I need to generate uuids.

```
07:16:49.070 [debug] Driver 'Elixir.BashoBench.Nebulex.Driver' crashed: {#{'__exception__' => true,'__struct__' => 'Elixir.Ecto.Query.CastError',message => <<"deps/ecto/lib/ecto/repo/queryable.ex:322: value `<<0, 0, 1, 244>>` cannot be dumped to type :binary_id in query:\n\nfrom w in Hello.World,\n  where: w.id == ^<<0, 0, 1, 244>>,\n  select: w\n">>,type => binary_id,value => <<0,0,1,244>>},[{'Elixir.Enum','-reduce/3-lists^foldl/2-0-',3,[{file,"lib/enum.ex"},{line,1826}]},{'Elixir.Enum','-map_reduce/3-lists^mapfoldl/2-0-',3,[{file,"lib/enum.ex"},{line,1372}]}]}
```

**Comment by fire** [comment]
I modified the schema so it works with integer keys, but I wanted uuid results. 
https://github.com/fire/database_cache_benchmark/commit/735852be657dd4b9ad6af9a39f40ad550d9b40b1

**Comment by fire** [comment]
![summary](https://user-images.githubusercontent.com/32321/31952695-131f9014-b896-11e7-90a2-60945f74b147.png)

Results on Windows and my desktop. Do not use this for scientific reference.

{operations, [{put, 1}, {get, 1}]}.

Currently trying:

{operations, [{put, 2}, {get, 8}]}.

**Comment by fire** [comment]
```erlang
{mode, max}.

{duration, 5}.

{concurrent, 8}.

{driver, 'Elixir.BashoBench.Nebulex.Driver'}.

{operations, [{put, 2}, {get, 8}]}.

{key_generator, {pareto_int, 1000}}.

{value_generator, {fixed_bin, 100000}}.
```
Results on Windows and my desktop. Do not use this for scientific reference.

![summary](https://user-images.githubusercontent.com/32321/31953592-3cead3b6-b898-11e7-8001-28b39f1ae772.png)

**Comment by fire** [comment]
Previous results are wrong, the puts were failing.

**Comment by fire** [comment]
![summary](https://user-images.githubusercontent.com/32321/31956177-760f6132-b89f-11e7-8d2a-3102ab5a7683.png)

```
{mode, max}.

{duration, 5}.

{concurrent, 36}.

{driver, 'Elixir.BashoBench.Nebulex.Driver'}.

{operations, [{put, 1}, {get, 1}]}.

{key_generator, {pareto_int, 1000}}.

{value_generator, {uniform_int, 10000}}.
```

**Comment by cabol** [comment]
These were my results, but only testing the cache, no Ecto (no DB access), I wanted to get some metrics from the Nebulex cache itself first. Keep in mind that you are testing Ecto with Nebulex, which means that for reads you fetch the data drom the DB sometimes, and for writes you always hit both, the cache and the DB.

But well, with your tests we have metrics from only `nebulex` and `nebulex_ecto` :)

Results:

<img width="844" alt="screen shot 2017-10-24 at 8 34 22 pm" src="https://user-images.githubusercontent.com/5407370/31956223-cef23e30-b8fb-11e7-8ac9-b1ad6015b032.png">

<img width="844" alt="screen shot 2017-10-24 at 8 36 41 pm" src="https://user-images.githubusercontent.com/5407370/31956229-d8ec3aee-b8fb-11e7-9d15-e755bb532ca2.png">

**Comment by fire** [comment]
I recommend we pick a few databases with standard hardware try out nebulex_ecto.

**Comment by cabol** [comment]
@fire 100% agreed, that would be great. Meanwhile, I'll create a separated project for these load tests (only for `nebulex`) – probably within `nebulex_examples` I'll create a new one, e.g.: `nebulex_bench`. Then, we can use your project `database_cache_benchmark` for `nebulex_ecto` load tests.

**Comment by cabol** [comment]
I've created a new project to run bench/load tests against `Nebulex`: [nebulex_bench](https://github.com/cabol/nebulex_examples/tree/master/nebulex_bench) – the project also contains some initial graphs with results for local cache.

**Comment by fire** [comment]
Interesting results trying to copy ycsb's 

```
Workload B: Read mostly workload
This workload has a 95/5 reads/write mix. Application example: photo tagging; add a tag is an update, but most operations are to read tags.
```

Hint. It mostly gets cached.

**Comment by cabol** [comment]
@fire based on you suggestion (pick a few databases with standard hardware try out `nebulex_ecto`), I just opened a new issue on [nebulex_ecto](https://github.com/cabol/nebulex_ecto) in order to continue the load tests but with `nebulex_ecto`. So I think this issue can be closed, let me know your thoughts!!

**Comment by fire** [comment]
That's a good suggestion. You can close this issue.
