### ISSUE TITLE
Question: disabling cache conditionally in defcacheable

### ISSUE THREAD

**Issue by fabiosantoscode** [cabol/nebulex#63]
Hello there!

I would like to turn a defcacheable function into a pass-through function when I'm in development, and turn on cache only in staging/production. My current environment is stored in the application config, so it's accessible at the time the macro is expanded. I'm a bit new at Elixir, so my attempt at a macro didn't prove very successful :)

The best solution I could come up with was to write a `_cached` variant of my function that calls an uncached variant, and then do this at every call site:

```
if @env == :dev do
  do_thing()
else
  do_thing_cached()
end
|> ...
```

But I was wondering if there is a built-in way of doing this.

**Comment by cabol** [comment]
Unfortunately, there isn't, that's a very specific use-case, so yes, it is something should be handled by you. The solution you came up with looks fine, overall if you want to address it at compile-time, you have to check the env to inject the desired behavior. Another similar option could be wrapping the whole function definition up, like:

```elixir
if @env == :dev do
  def my_funtion(id) do
    ...
  end
else
  defcacheable my_funtion(id), cache: ... do
    ...
  end
end
```

In that way, the env is not checked every time the function is executed.

**Comment by fabiosantoscode** [comment]
Cool, thanks!
