### ISSUE TITLE
Custom ttl for every cache record?

### ISSUE THREAD

**Issue by WolfDan** [cabol/nebulex#7]
One of the cool features of Cachex is set a custom ttl for every set record if is required, I don't see any possible way to achieve this on nebulex, just a global one that is "gc_interval" if I'm not wrong

So... Is possible to do it with Nebulex?

Greettings

**Comment by cabol** [comment]
@WolfDan of course it is possible:

```elixir
MyCache.set("foo", "bar", ttl: 5)
```

> `ttl` option is set in seconds

**Comment by WolfDan** [comment]
Oh nice, thank you!
