### ISSUE TITLE
MyCache.ttl/0 is undefined or private

### ISSUE THREAD

**Issue by steffenix** [cabol/nebulex#71]
It seems like the documentation is now outdated their is no `ttl/1` function on the `Nebulex.Cache` module.

Their is no function but the examples still contains it.

**Comment by cabol** [comment]
Sorry, where did you find the doc about the cache function `ttl/0`? may you point it me out, please?

**Comment by steffenix** [comment]
https://github.com/cabol/nebulex/blob/master/lib/nebulex/cache.ex#L835

**Comment by cabol** [comment]
Oh, I see, yes, that is a mistake, the function is `object_info/2`.

**Comment by cabol** [comment]
Fix already merged in master along with the base for v2.
