### ISSUE TITLE
mix nebulex.gen.cache replaces everything in folder.

### ISSUE THREAD

**Issue by PabloG6** [cabol/nebulex#75]
Just a heads up, the generator command which generates the cache for us actually deletes all existing files in the folder.

**Comment by cabol** [comment]
Thanks for the heads up! I'll check it out!

On the other hand, currently, I have removed the mix tasks from the v2, I was thinking to re-implement them, so I'll take advantage of that to check what is happening. Thanks!

**Comment by cabol** [comment]
Closing this issue because #97 should fix it. Feel free to re-open it if the problem persists.
