### ISSUE TITLE
opts[:stats] not getting through to the adapter

### ISSUE THREAD

**Issue by Ivor** [cabol/nebulex#78]
v2.0.0-rc

Configuring either the Replicated or Local cache with `stats: true` does not seem to pass this option through to the adapter, which means that stats do not seem to be collected.
If I edit the `child_spec` in `Nebulex.Cache` to manually insert the `stats` option then the `Stats` starts up and works as expected.

**Comment by cabol** [comment]
@Ivor may you provide more details, how are you configuring the `stats` option? For example, if we define:

```elixir
defmodule MyCache do
  use Nebulex.cache,
    otp_app: :my_app,
    adapter: Nebulex.Adapters.Local
end
```

And if we call `MyCache.start_link(stats: true)` that should work, or even by config file:

```elixir
config :my_app, MyCache,
  stats: true,
  ...
```

If you do something like that, it doesn't work for you? If you can give me more details would be awesome, thanks!

**Comment by Ivor** [comment]
@cabol thanks so much! I discovered that I had configured the cache incorrectly. I'm very excited about using Nebulex. 
Thanks for the great work!
