### ISSUE TITLE
Atom exhaustion from generations

### ISSUE THREAD

**Issue by danmcclain** [cabol/nebulex#8]
From a sufficiently long running app, the app will crash due to the dynamically generated atoms here: https://github.com/cabol/nebulex/blob/master/lib/nebulex/adapters/local/generation.ex#L125

**Comment by cabol** [comment]
@danmcclain good point, thanks! I'll try to fix it ASAP!!

**Comment by cabol** [comment]
@danmcclain I think this fix should works. It is a simple strategy, basically what I did was to force to use fixed number of atoms, which are initialized here: https://github.com/cabol/nebulex/blob/master/lib/nebulex/adapters/local/generation.ex#L114-L126

Then for cache generation names, re-use those fixed atoms (like a circular list): https://github.com/cabol/nebulex/blob/master/lib/nebulex/adapters/local/generation.ex#L128-L150. Suppose we have a 2 generations cache:

```
| Cache.0 |
| Cache.1 | Cache.0 |
| Cache.2 | Cache.1 |  # at this point generation Cache.0 was deleted so the atom can be re-used
| Cache.0 | Cache.2 |  # re-use Cache.0 and so on for next ones
```

Please take a look at it and let me know your thoughts and/or suggestions, stay tuned, thanks again :) !!
