### ISSUE TITLE
Is there a way to disable caching entirely?

### ISSUE THREAD

**Issue by rzane** [cabol/nebulex#87]
I can't seem to find a way to disable caching entirely.

Maybe this library could ship with a null adapter?

**Comment by cabol** [comment]
I hadn't thought of that, I agree it may be an interesting add-on. I will try to include it in the next release.

In the meantime, if you need to have a NULL adapter urgent, perhaps you can take the [AdapterMock](https://github.com/cabol/nebulex/blob/master/test/support/test_cache.ex#L104-L178) I have in the tests, you can just refactor it a bit, but I think you can do something similar.

**Comment by rzane** [comment]
Ahh, yeah, this looks like it would solve my issue. I mostly just want it so I don't have to think about caching when I'm running tests.

Thanks!

**Comment by cabol** [comment]
Created a separate issue for the NullAdapter #88
