### ISSUE TITLE
Adapters implementation guide

### ISSUE THREAD

**Issue by cabol** [cabol/nebulex#96]
Provide a guide to explain in detail and step by step how to implement a new adapter.

**Comment by thbar** [comment]
It would be interesting indeed. I wondered for instance how hard it would be to create a S3-backend to store large files & stream them back behind a proxy.

Not a urgent need, just sharing out a bit of idea!

**Comment by cabol** [comment]
Sounds interesting, but I'm not sure if a cache fits with this, since S3 is a distributed file system, meant to store files (files of any size), and on the other hand, Nebulex is a cache abstraction, and a cache is for in-memory storage, meant to store objects (ideally not large objects). Maybe I'm missing something, that's why I'd like to know more about the idea to understand how a Nebulex cache adapter may fit with S3. Stay tuned, thanks!
